name: New Feature
description: Keep track of an (approved) new feature of ampycloud
title: "[New Feature]: "
labels: ["todo"]
body:
  - type: markdown
    attributes:
      value: |
        This is to keep track of **dev-approved** changes.

        To **suggest** a new feature instead, head over to the [ampycloud Github Discussions page](https://github.com/MeteoSwiss/ampycloud/discussions).

  - type: textarea
    id: description
    attributes:
      label: Describe the new feature
      placeholder: Describe the feature
      value: "A clear and concise description of what should be added to || modified in || removed from ampycloud."
    validations:
      required: true
